name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        oscript_version: ['default', 'stable', 'dev']
        v8_version: ['8.3.24.1548', '8.3.23.1997']
    uses: segate-ekb/workflows/.github/workflows/test.yml@v1
    with:
      oscript_version: ${{ matrix.oscript_version }}
      v8_version: ${{matrix.v8_version}}